import React from "react";

export function Hello() {
  return <dl>
    <dt>o11y</dt>
    <dd>observability</dd>

    <dt>o11y (alternative <a href="https://en.wikipedia.org/wiki/Numeronym">numeronyms</a>)</dt>
    <dd>obedientially</dd>
    <dd>objectionably</dd>
    <dd>objurgatively</dd>
    <dd>objurgatorily</dd>
    <dd>obsolescently</dd>
    <dd>obstetrically</dd>
    <dd>obstructingly</dd>
    <dd>obstructively</dd>
    <dd>obstructivity</dd>
    <dd>occasionality</dd>
    <dd>occidentality</dd>
    <dd>octocentenary</dd>
    <dd>odontotherapy</dd>
    <dd>odoriferosity</dd>
    <dd>odoriferously</dd>
    <dd>offenselessly</dd>
    <dd>oligoprothesy</dd>
    <dd>omentorrhaphy</dd>
    <dd>omniactuality</dd>
    <dd>omnicausality</dd>
    <dd>omnicredulity</dd>
    <dd>omnifariously</dd>
    <dd>omnipresently</dd>
    <dd>omoplatoscopy</dd>
    <dd>omphalotripsy</dd>
    <dd>ontogenically</dd>
    <dd>ontologically</dd>
    <dd>openheartedly</dd>
    <dd>openmouthedly</dd>
    <dd>ophthalmology</dd>
    <dd>ophthalmotomy</dd>
    <dd>opinionatedly</dd>
    <dd>opisthography</dd>
    <dd>oppositionary</dd>
    <dd>opprobriously</dd>
    <dd>opsonotherapy</dd>
    <dd>opthalmoplegy</dd>
    <dd>opticociliary</dd>
    <dd>orchesography</dd>
    <dd>orchidoplasty</dd>
    <dd>orchiorrhaphy</dd>
    <dd>organomercury</dd>
    <dd>organotherapy</dd>
    <dd>originatively</dd>
    <dd>ornamentality</dd>
    <dd>ornithography</dd>
    <dd>ornithotrophy</dd>
    <dd>orthodoxality</dd>
    <dd>orthoepically</dd>
    <dd>orthogonality</dd>
    <dd>orthosymmetry</dd>
    <dd>oscillatively</dd>
    <dd>oscillography</dd>
    <dd>osphresiology</dd>
    <dd>ossiculectomy</dd>
    <dd>ostensibility</dd>
    <dd>otonecrectomy</dd>
    <dd>outstandingly</dd>
    <dd>overanxiously</dd>
    <dd>overbashfully</dd>
    <dd>overbearingly</dd>
    <dd>overbrutality</dd>
    <dd>overburningly</dd>
    <dd>overcarefully</dd>
    <dd>overcopiously</dd>
    <dd>overcorruptly</dd>
    <dd>overcredulity</dd>
    <dd>overcrowdedly</dd>
    <dd>overcunningly</dd>
    <dd>overcuriously</dd>
    <dd>overdemocracy</dd>
    <dd>overdevotedly</dd>
    <dd>overdiffusely</dd>
    <dd>overdistantly</dd>
    <dd>overdiversely</dd>
    <dd>overdiversify</dd>
    <dd>overdiversity</dd>
    <dd>overearnestly</dd>
    <dd>overelegantly</dd>
    <dd>overexcitably</dd>
    <dd>overexertedly</dd>
    <dd>overfavorably</dd>
    <dd>overfearfully</dd>
    <dd>overfertility</dd>
    <dd>overflowingly</dd>
    <dd>overfoolishly</dd>
    <dd>overforwardly</dd>
    <dd>overfrequency</dd>
    <dd>overgenerally</dd>
    <dd>overgeniality</dd>
    <dd>overhurriedly</dd>
    <dd>overintensely</dd>
    <dd>overintensity</dd>
    <dd>overjealously</dd>
    <dd>overlaudatory</dd>
    <dd>overlearnedly</dd>
    <dd>overliberally</dd>
    <dd>overlogically</dd>
    <dd>overnervously</dd>
    <dd>overobjectify</dd>
    <dd>overpainfully</dd>
    <dd>overpartially</dd>
    <dd>overpopularly</dd>
    <dd>overpreoccupy</dd>
    <dd>overpublicity</dd>
    <dd>overregularly</dd>
    <dd>overrunningly</dd>
    <dd>overseriously</dd>
    <dd>overservility</dd>
    <dd>overslavishly</dd>
    <dd>oversolemnity</dd>
    <dd>oversparingly</dd>
    <dd>overtediously</dd>
    <dd>overthriftily</dd>
    <dd>overweeningly</dd>
    <dd>overwillingly</dd>
    <dd>overzealously</dd>
    <dd>ovoviviparity</dd>
    <dd>oxidizability</dd>
  </dl>;
}
